import { CouponList } from '@/model/Coupon';
import { faker } from '@faker-js/faker';

export const allCoupons: CouponList = [
  {
    id: 1,
    store: '라오니 피자 강남점',
    menu: '콤비네이션 L 세트',
    category: '일식',
    discount: '20%',
    price: 24000,
    originalPrice: 30000,
    stock: 15,
    participated: 45,
    total: 60,
    walkTime: 10,
    distance: '0.6km',
    remainingTime: '14분',
    image: faker.image.url(),
    state: 'available', // 추가된 필드: 쿠폰 상태
  },
  {
    id: 2,
    store: '엄마 밥상 강남점',
    menu: '비빔밥 정식',
    category: '한식',
    discount: '20%',
    price: 8000,
    originalPrice: 10000,
    stock: 15,
    participated: 45,
    total: 60,
    walkTime: 10,
    distance: '0.6km',
    remainingTime: '112분',
    image: faker.image.url(),
    state: 'available', // 추가된 필드: 쿠폰 상태
  },
  {
    id: 3,
    store: '스시 마이 강남점',
    menu: '초밥 세트',
    category: '일식',
    discount: '20%',
    price: 24000,
    originalPrice: 30000,
    stock: 15,
    participated: 45,
    total: 60,
    walkTime: 10,
    distance: '0.6km',
    remainingTime: '14분',
    image: faker.image.url(),
    state: 'used', // 추가된 필드: 쿠폰 상태
  },
  {
    id: 4,
    store: '스시 마이 강남점',
    menu: '초밥 세트',
    category: '일식',
    discount: '20%',
    price: 24000,
    originalPrice: 30000,
    stock: 15,
    participated: 45,
    total: 60,
    walkTime: 10,
    distance: '0.6km',
    remainingTime: '14분',
    image: faker.image.url(),
    state: 'expired', // 추가된 필드: 쿠폰 상태
  },
];
